version: 0.1

phases:
  install:
    commands:
      - docker pull composer/composer:php7
  build:
    commands:
      - docker run -v `pwd`:/app composer/composer:php7 install
  post_build:
    commands:
      - |
        if [ -d build ]; then
           rm -Rf build/*
        else
           mkdir build
        fi
      - tar jcf --exclude=build/ build/zabix-$(date +%Y%m%d%H%m%S).tar.bz2 *
artifacts:
  files:
    - build*/**
  discard-paths: yes